const level1 = new Level(
    [   
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new ChickenSmall,
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Endboss()
    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud()
    ],
    [
        new BackgroundObject(ImageHub.background.air[0], -720),
        new BackgroundObject(ImageHub.background.third[1], -720),
        new BackgroundObject(ImageHub.background.second[1], -720),
        new BackgroundObject(ImageHub.background.first[1], -720),
        new BackgroundObject(ImageHub.background.air[0], 0),
        new BackgroundObject(ImageHub.background.third[0], 0),
        new BackgroundObject(ImageHub.background.second[0], 0),
        new BackgroundObject(ImageHub.background.first[0], 0),
        new BackgroundObject(ImageHub.background.air[0], 720),
        new BackgroundObject(ImageHub.background.third[1], 720),
        new BackgroundObject(ImageHub.background.second[1], 720),
        new BackgroundObject(ImageHub.background.first[1], 720),
        new BackgroundObject(ImageHub.background.air[0], 1440),
        new BackgroundObject(ImageHub.background.third[0], 1440),
        new BackgroundObject(ImageHub.background.second[0], 1440),
        new BackgroundObject(ImageHub.background.first[0], 1440),
        new BackgroundObject(ImageHub.background.air[0], 2160),
        new BackgroundObject(ImageHub.background.third[1], 2160),
        new BackgroundObject(ImageHub.background.second[1], 2160),
        new BackgroundObject(ImageHub.background.first[1], 2160),
        new BackgroundObject(ImageHub.background.air[0], 2880),
        new BackgroundObject(ImageHub.background.third[0], 2880),
        new BackgroundObject(ImageHub.background.second[0], 2880),
        new BackgroundObject(ImageHub.background.first[0], 2880)
    ],
    
);